services:
  nginx-pwa:
    image: nginx
    volumes:
      - ./src:/usr/share/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80
